import { en } from './en';

/**
 * German translations. Typed against `typeof en` so a missing/extra key is
 * a compile error, keeping the two dictionaries in lockstep.
 *
 * Tone: informal "du" throughout (health/wellness convention, and what the
 * original strings already used). Fixed glossary — Fasten, Ernährung,
 * Aktivität, Meditation, Statistik, Profil, Ziel, Gewicht, Größe,
 * Aktivitätslevel, Achtsamkeit — kept consistent across every screen.
 */
export const de: typeof en = {
  common: {
    back: 'Zurück',
    cancel: 'Abbrechen',
    close: 'Schließen',
    confirm: 'Bestätigen',
    continue: 'Weiter',
    done: 'Fertig',
    save: 'Speichern',
    saveChanges: 'Änderungen speichern',
    next: 'Weiter',
    skip: 'Überspringen',
    retry: 'Erneut versuchen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    add: 'Hinzufügen',
    remove: 'Entfernen',
    ok: 'OK',
    yes: 'Ja',
    no: 'Nein',
    loading: 'Wird geladen…',
  },
  errors: {
    generic: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
    network: 'Server nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.',
    bad_request: 'Die Anfrage konnte nicht verarbeitet werden.',
    unauthorized: 'Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.',
    forbidden: 'Dazu hast du keine Berechtigung.',
    not_found: 'Wir konnten nicht finden, wonach du gesucht hast.',
    validation: 'Einige der Angaben sind ungültig.',
    server: 'Auf unserer Seite ist etwas schiefgelaufen. Bitte versuche es gleich noch einmal.',
    cancelled: 'Die Anfrage wurde abgebrochen.',
    unknown: 'Ein unerwarteter Fehler ist aufgetreten.',
  },
  validation: {
    required: 'Dieses Feld ist erforderlich.',
    fieldRequired: '{{field}} ist erforderlich.',
    invalidEmail: 'Gib eine gültige E-Mail-Adresse ein.',
    passwordTooShort: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
    passwordsDontMatch: 'Die Passwörter stimmen nicht überein.',
  },
  language: {
    selectTitle: 'Wähle deine Sprache',
    selectSubtitle: 'Du kannst das später in den Einstellungen ändern.',
    continueCta: 'Weiter',
  },
  units: {
    cm: 'cm',
    kg: 'kg',
    kcal: 'kcal',
    min: 'Min.',
    minShort: 'Min.',
    hoursShort: 'Std.',
    daysShort: 'T',
    perWeek: '/Woche',
    tracked: '{{count}} verfolgt',
  },
  enums: {
    goal: {
      weight_loss: 'Abnehmen',
      maintenance: 'Gewicht halten',
      general_wellness: 'Allgemeines Wohlbefinden',
      muscle_gain: 'Muskelaufbau',
    },
    goalAction: {
      weight_loss: 'Abnehmen',
      maintenance: 'Gewicht halten',
      muscle_gain: 'Zunehmen',
    },
    activityLevel: {
      sedentary: 'Sitzend',
      light: 'Leicht aktiv',
      moderate: 'Mäßig aktiv',
      active: 'Sehr aktiv',
      very_active: 'Extrem aktiv',
    },
    gender: {
      female: 'Weiblich',
      male: 'Männlich',
      diverse: 'Divers / Andere',
    },
    meal: {
      breakfast: 'Frühstück',
      lunch: 'Mittagessen',
      dinner: 'Abendessen',
      snack: 'Snack',
      custom: 'Eigene',
    },
    meditationMode: {
      guided: 'Geführt',
      free: 'Unbegleitet',
      breathing: 'Atmung',
    },
    meditationTopic: {
      morning: 'Morgen',
      mindfulness: 'Achtsamkeit',
      energy: 'Energie',
      focus: 'Fokus & Konzentration',
      relaxation: 'Entspannung',
      calm: 'Ruhe',
      stress_relief: 'Stressabbau',
      sleep: 'Schlaf',
    },
    meditationSoundCategory: {
      meditation_music: 'Meditationsmusik',
      ambient: 'Ambient-Klänge',
      nature: 'Naturklänge',
    },
  },
  tabs: {
    home: 'Start',
    profile: 'Profil',
    fasting: 'Fasten',
    nutrition: 'Ernährung',
    activity: 'Aktivität',
    meditation: 'Meditation',
    statistics: 'Statistik',
  },
  nav: {
    goHome: 'Zur Startseite',
  },
  splash: {
    tagline: 'Fasten · Ernährung · Aktivität · Meditation',
  },
  home: {
    greeting: {
      morning: 'Guten Morgen',
      afternoon: 'Guten Tag',
      evening: 'Guten Abend',
    },
    pulse: {
      title: 'Dein Tag im Überblick',
      onTrack: 'Auf Kurs',
      goalExceeded: 'Ziel überschritten',
      kcalRemaining: 'kcal übrig',
      kcalOver: 'kcal über dem Ziel',
      fastingStreak: '{{days}} Tage Fasten-Serie',
      mindfulStreak: '{{days}} Tage Achtsamkeits-Serie',
    },
    ring: {
      nutrition: 'Ernährung',
      activity: 'Aktivität',
      mindfulness: 'Achtsamkeit',
    },
    today: {
      title: 'Heute',
      consumedToday: 'Heute aufgenommen',
      activity: 'Aktivität',
      meditation: 'Meditation',
      streak: 'Serie',
      netKcal: 'Netto kcal',
    },
  },
  history: {
    title: 'Verlauf',
    allGoals: 'Alle Ziele',
    emptyTitle: 'Noch kein Verlauf',
    emptyMessage: 'Aktivitäten aus allen {{appName}}-Bereichen erscheinen hier.',
    filters: {
      fasting: 'Fasten',
      nutrition: 'Ernährung',
      activity: 'Aktivität',
      weight: 'Gewicht',
      meditation: 'Meditation',
    },
  },
  onboarding: {
    stepProgress: 'Schritt {{step}} von {{total}}',
    welcome: {
      tagline: 'Deine Gesundheit, im Einklang.',
      begin: 'Start',
      wellness: 'Wohlbefinden',
    },
    goals: {
      heading: 'Was führt dich zu HealthyMe?',
      subheading: 'Wähle aus, worauf du dich konzentrieren möchtest. Wir passen deine Erfahrung entsprechend an.',
      recommendation: 'Wähle bis zu 3 zum Start — du kannst jederzeit mehr hinzufügen.',
      items: {
        fitness: { title: 'Fit werden & Kraft aufbauen', subtitle: 'Training, Kraft, Struktur' },
        activity: { title: 'Aktiver werden', subtitle: 'Jeden Tag mehr bewegen' },
        yoga: { title: 'Yoga praktizieren', subtitle: 'Beweglichkeit & achtsame Bewegung' },
        meditation: { title: 'Meditieren & sich besser fühlen', subtitle: 'Ruhe, Fokus, besserer Schlaf' },
        fasting: { title: 'Mein Fasten verbessern', subtitle: 'Einen Rhythmus finden, der zu dir passt' },
        nutrition: { title: 'Besser essen', subtitle: 'Verfolge und verbessere deine Ernährung' },
        overall: { title: 'Allgemeine Gesundheit verbessern', subtitle: 'Ein bisschen von allem' },
      },
      primary: {
        eyebrow: 'HAUPTFOKUS',
        title: 'Was ist gerade dein Hauptfokus?',
        subtitle: 'Der Rest bleibt trotzdem Teil deiner Erfahrung — das entscheidet nur, was zuerst kommt.',
      },
    },
    goalQuestions: {
      fitness: {
        level: {
          title: 'Wie ist dein Fitnesslevel?',
          options: { beginner: 'Anfänger', intermediate: 'Mittelstufe', advanced: 'Fortgeschritten' },
        },
        where: {
          title: 'Wo trainierst du normalerweise?',
          options: { home: 'Zuhause', gym: 'Im Fitnessstudio', both: 'Beides' },
        },
        targets: {
          title: 'Woran arbeitest du?',
          options: { muscle: 'Muskeln aufbauen', fat_loss: 'Fett verlieren', strength: 'Stärker werden', fitness: 'Fitness verbessern', consistency: 'Konstant bleiben' },
        },
        frequency: {
          title: 'Wie oft möchtest du trainieren?',
          options: { two: '2 Tage/Woche', three: '3 Tage/Woche', four: '4 Tage/Woche', five_plus: '5+ Tage/Woche' },
        },
      },
      activity: {
        enjoy: {
          title: 'Welche Aktivitäten machst du gerne?',
          options: { walking: 'Gehen', running: 'Laufen', cycling: 'Radfahren', hiking: 'Outdoor-Aktivität', other: 'Allgemeine Bewegung' },
        },
        improve: {
          title: 'Was möchtest du verbessern?',
          options: { daily_movement: 'Tägliche Bewegung', endurance: 'Ausdauer', distance: 'Distanz', pace: 'Tempo', consistency: 'Konstanz' },
        },
      },
      yoga: {
        experience: {
          title: 'Wie viel Yoga-Erfahrung hast du?',
          options: { new: 'Neu bei Yoga', some: 'Etwas Erfahrung', regular: 'Regelmäßige Praxis' },
        },
        focus: {
          title: 'Was möchtest du von Yoga?',
          options: { flexibility: 'Beweglichkeit', mobility: 'Mobilität', relaxation: 'Entspannung', strength: 'Kraft', balance: 'Balance', stress_relief: 'Stressabbau' },
        },
        sessionLength: {
          title: 'Wie lang sollte eine typische Einheit sein?',
          options: { short: '5–10 Min.', medium: '15–20 Min.', long: '30 Min.', extended: '45+ Min.' },
        },
      },
      meditation: {
        help: {
          title: 'Wobei soll Meditation dir helfen?',
          options: { stress_relief: 'Stressabbau', sleep: 'Besserer Schlaf', focus: 'Fokus & Konzentration', calm: 'Ruhe', mindfulness: 'Achtsamkeit', energy: 'Energie', relaxation: 'Entspannung' },
        },
        familiarity: {
          title: 'Wie vertraut bist du mit Meditation?',
          options: { new: 'Ich bin neu dabei', tried: 'Ich habe es schon probiert', regular: 'Ich meditiere regelmäßig' },
        },
        sessionLength: {
          title: 'Welche Sitzungslänge fühlt sich richtig an?',
          options: { five: '5 Min.', fifteen: '15 Min.', thirty: '30 Min.', forty_five_plus: '45+ Min.' },
        },
      },
      fasting: {
        familiarity: {
          title: 'Wie vertraut bist du mit Fasten?',
          options: { new: 'Ich bin neu dabei', tried: 'Ich habe Fasten schon probiert', regular: 'Ich faste regelmäßig' },
        },
        lookingFor: {
          title: 'Wonach suchst du?',
          options: { routine: 'Eine Routine aufbauen', track: 'Fastenzeit verfolgen', consistency: 'Konstanz verbessern', explore: 'Fastenpläne entdecken' },
        },
        schedule: {
          title: 'Welcher Fastenplan interessiert dich?',
          options: { fourteen_ten: '14:10', sixteen_eight: '16:8', eighteen_six: '18:6', twenty_four: '20:4' },
        },
      },
      nutrition: {
        focus: {
          title: 'Worauf möchtest du dich konzentrieren?',
          options: { eat_healthier: 'Gesünder essen', track_calories: 'Kalorien verfolgen', protein: 'Proteinzufuhr verbessern' },
        },
      },
      overall: {
        matters: {
          title: 'Was ist dir am wichtigsten?',
          options: { move: 'Mehr bewegen', eat: 'Besser essen', sleep: 'Besser schlafen/entspannen', consistency: 'Konstanz aufbauen', fitness: 'Fitness verbessern', mindfulness: 'Achtsamkeit' },
        },
      },
    },
    goalSummary: {
      title: 'HealthyMe ist bereit für dich.',
      yourFocus: 'Dein Fokus',
      body: 'Deine Erfahrung konzentriert sich auf {{items}}.',
      blurbs: {
        fitness: 'Krafttraining',
        activity: 'tägliche Bewegung',
        yoga: 'achtsame Bewegung',
        meditation: 'kurze Achtsamkeitsübungen',
        fasting: 'einen Fastenrhythmus, der zu dir passt',
        nutrition: 'Ernährungs-Tracking',
        overall: 'eine ausgewogene Routine über alle Bereiche',
      },
      continueCta: 'Weiter',
    },
    goal: {
      eyebrow: 'DEIN ZIEL',
      title: 'Was möchtest du erreichen?',
      options: {
        weight_loss: { title: 'Abnehmen', outcome: 'Ein stetiges Kaloriendefizit, direkt in dein Tagesziel eingebaut.' },
        maintenance: { title: 'Gewicht halten', outcome: 'Bleib stabil — deine Ziele folgen genau deinem Ausgangswert.' },
        muscle_gain: { title: 'Zunehmen', outcome: 'Ein kontrollierter Überschuss für Muskeln, nicht nur für die Waage.' },
      },
    },
    personalize: {
      title: 'Dein Profil',
      next: 'Los geht’s',
      subtitle: 'Ein paar kurze Angaben und {{appName}} {{tagline}}.',
      whatWeUse: 'Was wir verwenden',
      taglineFallback: 'hilft dir, einen Plan zu erstellen, der wirklich passt',
      taglines: {
        weight_loss: 'hilft dir, ein stetiges Abnehmziel zu erreichen',
        maintenance: 'hilft dir, genau da stabil zu bleiben, wo du bist',
        muscle_gain: 'hilft dir beim Aufbau, mit einem Ziel, das das unterstützt',
      },
      items: {
        body: 'Ein paar Körper-Basiswerte',
        birthday: 'Dein Geburtstag',
        nutrients: 'Welche Nährstoffe wichtig sind',
      },
    },
    gender: {
      title: 'Fangen wir mit dir an',
      subtitle: 'Das kalibriert deine Basisberechnungen.',
    },
    age: {
      title: 'Wann hast du Geburtstag?',
      subtitle: 'Wird zur Kalibrierung deiner Basiswerte verwendet.',
      label: 'Geburtsdatum',
    },
    height: {
      title: 'Wie groß bist du?',
      subtitle: 'Zieh, um deine Größe einzustellen — dein Profil skaliert mit.',
      info: 'Mit deiner Größe können wir deinen Kalorienverbrauch berechnen.',
    },
    weight: {
      title: 'Was ist dein Gewicht?',
      subtitle: 'Zieh, um dein aktuelles Gewicht einzustellen.',
      info: 'Aus Gewicht und Größe schätzt der Algorithmus deinen ungefähren Körperfettanteil.',
      reassurance: 'Eine visuelle Orientierung für dein Profil — niemals ein Urteil.',
    },
    activityLevel: {
      title: 'Wie aktiv bist du?',
      subtitle: 'Fließt in deinen geschätzten Tagesbedarf ein.',
      options: {
        sedentary: { desc: 'Kaum bis kein Sport, Bürojob.' },
        light: { desc: 'Leichter Sport 1–3 Tage pro Woche.' },
        moderate: { desc: 'Mäßiger Sport 3–5 Tage pro Woche.' },
        active: { desc: 'Intensiver Sport 6–7 Tage pro Woche.' },
        very_active: { desc: 'Körperlicher Job oder zweimal tägliches Training.' },
      },
    },
    micronutrients: {
      title: 'Mikronährstoffe einrichten',
      subtitle: 'Wir haben ausgewählt, was für dein Ziel am wichtigsten ist — tippe zum Anpassen.',
      next: 'Meinen Plan erstellen',
      trackedOf: 'von {{count}} Nährstoffen verfolgt',
      categories: {
        vitamins: 'Vitamine',
        minerals: 'Mineralstoffe',
        other: 'Weitere Essenzielle',
      },
    },
    complete: {
      readyTitle: 'Dein Plan ist bereit',
      readySubtitle: 'Aus deinem Profil erstellt — jede Zahl unten passt sich an, während du weitermachst.',
      dailyCalorieTarget: 'Tägliches Kalorienziel',
      statuses: {
        analyzing: 'Dein Profil wird analysiert…',
        calculating: 'Dein Ausgangswert wird berechnet…',
        personalizing: 'Dein Plan wird personalisiert…',
      },
      goal: 'Ziel',
      activityLevel: 'Aktivitätslevel',
      heightWeight: 'Größe · Gewicht',
      micronutrients: 'Mikronährstoffe',
      carbs: 'Kohlenhydrate',
      protein: 'Protein',
      fat: 'Fett',
      enter: '{{appName}} starten',
    },
  },
  auth: {
    mockNotice: 'Die Anmeldung ist für diesen Prototyp lokal simuliert.',
    login: {
      title: 'Willkommen zurück',
      subtitle: 'Melde dich an, um deine {{appName}}-Routine fortzusetzen.',
      email: 'E-Mail',
      emailPlaceholder: 'Gib deine E-Mail ein',
      password: 'Passwort',
      passwordPlaceholder: 'Gib dein Passwort ein',
      emailInvalid: 'Bitte gib eine gültige E-Mail-Adresse ein.',
      passwordRequired: 'Bitte gib dein Passwort ein.',
      forgotPassword: 'Passwort vergessen?',
      submit: 'Anmelden',
      newToApp: 'Neu bei {{appName}}?',
      createAccount: 'Konto erstellen',
    },
    register: {
      title: 'Konto erstellen',
      firstName: 'Vorname',
      lastName: 'Nachname',
      email: 'E-Mail',
      password: 'Passwort',
      submit: 'Konto erstellen',
      haveAccount: 'Du hast bereits ein Konto?',
      logIn: 'Anmelden',
    },
    forgotPassword: {
      title: 'Passwort zurücksetzen',
      intro: 'Gib die E-Mail-Adresse deines Kontos ein und wir senden dir eine Anleitung zum Zurücksetzen.',
      email: 'E-Mail',
      submit: 'Link zum Zurücksetzen senden',
      sent: 'Falls ein Konto für {{email}} existiert, wurde ein Link zum Zurücksetzen gesendet.',
    },
    address: {
      title: 'Wohin sollen wir liefern?',
      subtitle: 'Wird für den {{appName}}-Webshop verwendet — Bestellungen und Lieferungen.',
      label: 'Straße, Ort, Postleitzahl',
      submit: 'Weiter',
    },
    emailVerification: {
      title: 'E-Mail bestätigen',
      verifiedTitle: 'E-Mail bestätigt',
      sentTo: 'Wir haben einen Bestätigungslink an {{email}} gesendet.',
      yourEmail: 'deine E-Mail',
      verifiedBody: 'Dein Konto ist vollständig eingerichtet.',
      verifiedButton: 'Ich habe meine E-Mail bestätigt',
    },
  },
  profile: {
    title: 'Profil',
    height: 'Größe',
    weight: 'Gewicht',
    activityLevel: 'Aktivitätslevel',
    goal: 'Ziel',
    editProfile: 'Profil bearbeiten',
    settings: 'Einstellungen',
    healthIntegrations: 'Gesundheits-Integrationen',
    sendFeedback: 'Feedback senden',
    privacy: 'Datenschutz',
    logout: 'Abmelden',
    goBack: 'Zurück',
  },
  editProfile: {
    title: 'Profil bearbeiten',
    firstName: 'Vorname',
    lastName: 'Nachname',
    heightCm: 'Größe (cm)',
    weightKg: 'Gewicht (kg)',
    profilePicture: 'Profilbild',
    changePhoto: 'Profilbild ändern',
    initial: 'Initiale',
    save: 'Änderungen speichern',
  },
  avatarPicker: {
    title: 'Wähle deinen Avatar',
    subtitle: 'Wähle ein Motiv oder behalte deine Initiale',
    useInitial: 'Initiale verwenden',
    initial: 'Initiale',
    avatarLabel: 'Avatar {{name}}',
    cancel: 'Abbrechen',
    done: 'Fertig',
  },
  settings: {
    title: 'Einstellungen',
    appearance: 'Darstellung',
    theme: {
      light: 'Hell',
      dark: 'Dunkel',
      system: 'System',
    },
    units: {
      title: 'Einheiten',
      metric: 'Metrisch',
      imperial: 'Imperial',
    },
    language: {
      title: 'Sprache',
    },
    liveMoments: {
      title: 'Fasten-Timeline „Live-Momente“',
      showCards: 'Live-Moment-Karten anzeigen',
      haptics: 'Haptisches Feedback',
    },
    data: {
      title: 'Daten',
      healthIntegrations: 'Gesundheits-Integrationen',
      privacy: 'Datenschutz & Daten',
      dataManagement: 'Datenverwaltung',
    },
    support: {
      title: 'Support',
      feedback: 'Feedback senden',
    },
  },
  notifications: {
    title: 'Benachrichtigungen',
    empty: 'Noch keine Benachrichtigungen',
    emptyMessage: 'Erinnerungen und Meilensteine erscheinen hier.',
    markAllRead: 'Alle als gelesen markieren',
  },
  fasting: {
    title: 'Fasten',
    startFast: 'Fasten starten',
    viewActiveFast: 'Aktives Fasten ansehen',
    startFastShort: 'Fasten starten',
    active: 'Aktiv',
    noActiveFast: 'Kein aktives Fasten',
    noActiveFastBody: 'Wähle eine Methode und beginne, dein Fastenfenster zu verfolgen.',
    elapsed: '{{duration}} vergangen',
    goalTimeReached: 'Zielzeit erreicht',
    remaining: 'noch {{duration}}',
    plannedEnd: '{{duration}} · geplantes Ende um {{time}}',
    stats: {
      currentStreak: 'Aktuelle Serie',
      completed: 'Abgeschlossen',
      avgDuration: 'Ø Dauer',
      longest: 'Längste',
    },
    menu: {
      history: 'Fasten-Verlauf',
      calendar: 'Fasten-Kalender',
      statistics: 'Fasten-Statistik',
      plans: 'Meine Fastenpläne',
      settings: 'Fasten-Einstellungen',
    },
    chooseMethod: 'Methode wählen',
  },
  nutrition: {
    title: 'Ernährung',
    noItemsLogged: 'Nichts erfasst',
    itemsSummary: '{{kcal}} kcal · {{count}} Einträge',
    ofKcal: 'von {{target}} kcal',
    kcalRemaining: '{{amount}} kcal übrig',
    goalExceededBy: 'Ziel um {{amount}} kcal überschritten',
    emptyTitle: 'Noch nichts erfasst',
    emptyMessage: 'Füge deine erste Mahlzeit hinzu, um die Ernährung von heute zu sehen.',
    quickAddTitle: 'Schnell hinzufügen',
    endFastPrompt: {
      title: 'Du hast ein aktives Fasten',
      message: 'Essen zu erfassen bedeutet meist, dass ein Essensfenster begonnen hat. Dein aktuelles Fasten jetzt beenden?',
      keepFasting: 'Weiter fasten',
      endFast: 'Fasten beenden',
    },
    quickAdd: {
      barcode: 'Barcode scannen',
      aiPhoto: 'KI-Foto',
      aiVoice: 'KI-Sprache',
      aiText: 'KI-Text',
    },
    menu: {
      recipes: 'Meine Rezepte',
      foods: 'Meine Lebensmittel',
      favorites: 'Favoriten',
      goals: 'Ernährungsziele',
      history: 'Ernährungsverlauf',
    },
    macros: {
      carbs: 'Kohlenhydrate',
      protein: 'Protein',
      fat: 'Fett',
    },
  },
  activity: {
    title: 'Aktivität',
    startActivity: 'Aktivität starten',
    logManually: 'Manuell erfassen',
    viewAllActivity: 'Alle Aktivitäten ansehen',
    viewFullHistory: 'Vollständigen Verlauf ansehen',
    recentActivities: 'Letzte Aktivitäten',
    inProgress: '{{type}} läuft',
    tapToResume: 'Tippe, um das Tracking fortzusetzen',
    emptyTitle: 'Noch keine Aktivitäten',
    emptyMessage: 'Starte ein Workout oder erfasse eines manuell, um es hier zu sehen.',
    start: 'Start',
    pause: 'Pause',
    resume: 'Fortsetzen',
    finish: 'Beenden',
    distance: 'Distanz',
    pace: 'Tempo',
    duration: 'Dauer',
  },
  meditation: {
    title: 'Meditation',
    findYourCalm: 'Finde deine Ruhe',
    subtitle: 'Meditation für ein besseres Ich',
    today: 'Heute',
    streak: 'Serie',
    dayShort: 'Tag',
    startMeditation: 'Meditation starten',
    quickSessions: 'Kurz-Sitzungen',
    viewAll: 'Alle ansehen',
    viewAllQuickSessions: 'Alle Kurz-Sitzungen ansehen',
    quick: {
      short: 'Kurz',
      shortSub: '3 Min.',
      guided: 'Geführt',
      guidedSub: 'Sitzungen',
      breathing: 'Atmung',
      breathingSub: 'Übungen',
      free: 'Unbegleitet',
      freeSub: 'Meditieren',
    },
    menu: {
      templates: 'Meine Vorlagen',
      templatesSub: 'Deine gespeicherten Meditationen',
      goals: 'Ziele',
      goalsSub: 'Verfolge deinen Fortschritt',
      history: 'Verlauf',
      historySub: 'Deine vergangenen Sitzungen',
      statistics: 'Statistik',
      statisticsSub: 'Einblicke und Trends',
      reminders: 'Erinnerungen',
      remindersSub: 'Bleib dran',
    },
    exitConfirm: {
      title: 'Meditation beenden?',
      message: 'Möchtest du diese Meditationssitzung wirklich verlassen?',
      continue: 'Meditation fortsetzen',
      end: 'Sitzung beenden',
    },
    ambient: {
      control: 'Hintergrundklang',
      title: 'Klangkulisse',
      subtitle: 'Optionaler Hintergrundklang für diese Sitzung',
      none: 'Kein Klang',
      recommended: 'Empfohlen',
      comingSoon: 'Demnächst',
      unavailable: 'Hintergrundklang nicht verfügbar — Sitzung läuft ohne ihn weiter',
      volume: 'Lautstärke',
      sounds: {
        rain: 'Regen',
        ocean: 'Meer',
        forest: 'Wald',
        fire: 'Kaminfeuer',
        ambient: 'Ambient',
      },
    },
    player: {
      comingSoonBody: 'Diese Sitzung kommt bald.',
      wellDone: 'Gut gemacht',
      minCompleted: '{{minutes}} Min. abgeschlossen',
      ofMin: 'von {{minutes}} Min.',
      preparing: 'Deine Meditation wird vorbereitet…',
      audioUnavailable: 'Audio nicht verfügbar — Sitzung läuft ohne Ton weiter',
      pause: 'Pause',
      resume: 'Fortsetzen',
      fallbackTitle: 'Meditation',
      unguidedFallbackTitle: 'Unbegleitete Meditation',
    },
    details: {
      notFoundTitle: 'Meditation',
      unavailableTitle: 'Meditation nicht verfügbar',
      unavailableBody: 'Dieser Inhalt wurde möglicherweise deaktiviert oder archiviert.',
      removeFavorite: 'Aus Favoriten entfernen',
      addFavorite: 'Zu Favoriten hinzufügen',
      comingSoon: 'Demnächst',
      start: 'Meditation starten',
    },
    categories: {
      all: 'Alle',
      guidedTitle: 'Geführte Meditationen',
      unguidedTitle: 'Unbegleitete Meditationen',
      tryMeditationMusic: 'Meditationsmusik ausprobieren',
      clearFilters: 'Filter zurücksetzen',
      showAllTopic: 'Alle für {{topic}} anzeigen',
      descriptorDuration: '{{minutes}}-minütige Sitzung',
      descriptorSound: '{{sound}}-Sitzung',
      descriptorDurationSound: '{{minutes}}-minütige {{sound}}-Sitzung',
      emptyGeneric: 'Noch nichts verfügbar.',
      emptyForTopic: 'Für {{topic}} ist noch nichts verfügbar.',
      emptyWithDescriptor: 'Es ist noch keine {{descriptor}} verfügbar.',
      emptyForTopicWithDescriptor: 'Für {{topic}} ist noch keine {{descriptor}} verfügbar.',
    },
    favoritesScreen: {
      title: 'Favoriten',
      empty: 'Noch keine Favoriten',
    },
    historyScreen: {
      title: 'Meditationsverlauf',
      empty: 'Noch keine Sitzungen',
      statusCompleted: 'Abgeschlossen',
      statusEndedEarly: 'Vorzeitig beendet',
    },
    statisticsScreen: {
      title: 'Meditationsstatistik',
      noData: 'Noch keine Daten verfügbar.',
      totalSessions: 'Sitzungen insgesamt',
      totalTime: 'Gesamtzeit',
      averageDuration: 'Durchschnittliche Dauer',
      longestSession: 'Längste Sitzung',
      currentStreak: 'Aktuelle Serie',
    },
    remindersScreen: {
      title: 'Erinnerungen',
      disclaimer: 'Erinnerungen zählen nicht als abgeschlossene Meditation — sie sind nur ein Anstoß.',
      time: 'Uhrzeit',
      days: 'Wiederholen an',
      add: 'Erinnerung hinzufügen',
      empty: 'Noch keine Meditations-Erinnerungen',
      everyDay: 'Jeden Tag',
      weekdays: 'Wochentage',
      selectAtLeastOneDay: 'Wähle mindestens einen Tag aus.',
      savingWhileOff: 'Diese Erinnerung ist aus — Speichern lässt sie aus. Nutze den Schalter, um sie zu aktivieren.',
      permissionDenied: 'Benachrichtigungen sind für {{appName}} deaktiviert, daher kann diese Erinnerung nicht geplant werden. Aktiviere Benachrichtigungen in den Geräteeinstellungen, um sie zu aktivieren.',
      notificationTitle: 'Zeit für deine Meditation',
      notificationBody: 'Nimm dir ein paar Minuten für dich.',
    },
    goalsScreen: {
      title: 'Meditationsziele',
      goalExceeded: 'Ziel übertroffen',
      type: {
        meditation_minutes: 'Meditationsminuten',
        meditation_sessions: 'Meditationssitzungen',
      },
    },
    templatesScreen: {
      title: 'Meine Vorlagen',
      newTemplate: 'Neue Vorlage',
      name: 'Name',
      durationMinutes: 'Dauer (Minuten)',
      saveTemplate: 'Vorlage speichern',
      empty: 'Noch keine Vorlagen',
      emptyBody: 'Speichere eine persönliche Meditationskonfiguration, um sie mit einem Tipp wiederzuverwenden.',
    },
    breathing: {
      unavailable: 'Atemübung nicht verfügbar',
      getComfortable: 'Mach es dir bequem',
      breatheIn: 'Einatmen',
      hold: 'Halten',
      breatheOut: 'Ausatmen',
      ready: 'Bereit',
      start: 'Atemübung starten',
      stop: 'Stopp',
      wellDone: 'Gut gemacht',
      cycleProgress: 'Zyklus {{current}} von {{total}}',
      voiceGuidanceOn: 'Sprachführung an',
      voiceGuidanceOff: 'Sprachführung aus',
      background: {
        none: 'Kein Klang',
        meditationMusic: 'Meditationsmusik',
        ambient: 'Ambient',
        nature: 'Natur',
      },
    },
  },
  statistics: {
    title: 'Statistik',
    noData: 'Noch nicht genug Daten',
    period: {
      day: 'Tag',
      week: 'Woche',
      month: 'Monat',
      year: 'Jahr',
      total: 'Gesamt',
    },
  },
  weight: {
    loggedOn: 'Erfasst am {{date}}',
    noEntries: 'Noch keine Einträge',
    manual: 'Manuell',
  },
  feedback: {
    title: 'Feedback',
    intro: 'Wir lesen jede Nachricht — sag uns, was gut funktioniert oder was nicht.',
    category: {
      improvement: {
        title: 'Verbesserung vorschlagen',
        description: 'Etwas funktioniert, könnte aber besser sein.',
      },
      bug: {
        title: 'Fehler melden',
        description: 'Etwas ist kaputt oder verhält sich unerwartet.',
      },
      feature: {
        title: 'Funktion vorschlagen',
        description: 'Etwas, das sich {{appName}} wünschen würde.',
      },
      general: {
        title: 'Allgemeines Feedback',
        description: 'Alles andere, das dir am Herzen liegt.',
      },
    },
    messageLabel: 'Deine Nachricht',
    messagePlaceholder: 'Erzähl uns mehr…',
    validationRequired: 'Bitte gib eine Nachricht ein, bevor du absendest.',
    submit: 'Feedback senden',
    submitting: 'Wird gesendet…',
    success: {
      title: 'Danke dir',
      body: 'Dein Feedback ist angekommen — es hilft uns wirklich dabei, das Nächste zu gestalten.',
      done: 'Fertig',
    },
  },
  states: {
    errorTitle: 'Etwas ist schiefgelaufen',
    errorBody: 'Bitte versuche es erneut.',
    retry: 'Erneut versuchen',
    emptyTitle: 'Hier ist noch nichts',
  },
};
