/**
 * English source-of-truth dictionary.
 *
 * `de.ts` is typed `: typeof en`, so every key here must also exist there —
 * `tsc` fails the build on any drift.
 *
 * Coverage as of the localization pass: the first-launch language flow, the
 * whole onboarding + auth journey, the Profile / Edit Profile / Settings /
 * Notifications / History / Goals screens, the tab bar, the avatar picker,
 * shared empty/error/loading/dialog components, and every section's landing
 * screen (Fasting / Nutrition / Activity / Meditation homes — headers, menu
 * rows, stat labels, empty states, primary CTAs).
 *
 * Still hardcoded English, translated in a follow-up pass with the same
 * `t()` pattern:
 *  - deep per-section sub-screens: FoodSearch, most of AddFood, ActiveFast,
 *    FastSummary, FastingHistory/Calendar/Plans/Settings/Statistics,
 *    ActiveActivity/ActivitySummary/ActivityHistory/Details/Manual,
 *    Meditation Categories/Details/Player body/History/Statistics/Templates/
 *    Goals/Reminders, the Statistics tab, home/{HealthIntegrations,Privacy,
 *    DataManagement,NoiseDevice,EnterWeight}
 *  - content-data corpora: `mock/*Seed.ts`, `features/fasting/fastingTimelineContent.ts`,
 *    `features/onboarding/data/micronutrients.ts` blurbs, activity-type and
 *    goal-feature label maps, avatar preset motif names
 *  - Redux-stored `auth` error strings (need the thunk to expose an error
 *    `kind` before `t('errors.<kind>')` can be applied at the call site)
 */
export const en = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    continue: 'Continue',
    done: 'Done',
    save: 'Save',
    saveChanges: 'Save changes',
    next: 'Next',
    skip: 'Skip',
    retry: 'Retry',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    remove: 'Remove',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading…',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Unable to reach the server. Check your connection and try again.',
    bad_request: 'The request could not be processed.',
    unauthorized: 'Your session has expired. Please log in again.',
    forbidden: "You don't have permission to do that.",
    not_found: 'We couldn’t find what you were looking for.',
    validation: 'Some of the information provided is invalid.',
    server: 'Something went wrong on our end. Please try again shortly.',
    cancelled: 'The request was cancelled.',
    unknown: 'An unexpected error occurred.',
  },
  validation: {
    required: 'This field is required.',
    fieldRequired: '{{field}} is required.',
    invalidEmail: 'Enter a valid email address.',
    passwordTooShort: 'Password must be at least 8 characters.',
    passwordsDontMatch: 'Passwords don’t match.',
  },
  language: {
    selectTitle: 'Choose your language',
    selectSubtitle: 'You can change this later in Settings.',
    continueCta: 'Continue',
  },
  units: {
    cm: 'cm',
    kg: 'kg',
    kcal: 'kcal',
    min: 'min',
    minShort: 'min',
    hoursShort: 'h',
    daysShort: 'd',
    perWeek: '/week',
    tracked: '{{count}} tracked',
  },
  enums: {
    goal: {
      weight_loss: 'Weight loss',
      maintenance: 'Maintenance',
      general_wellness: 'General wellness',
      muscle_gain: 'Muscle gain',
    },
    goalAction: {
      weight_loss: 'Lose weight',
      maintenance: 'Maintain weight',
      muscle_gain: 'Gain weight',
    },
    activityLevel: {
      sedentary: 'Sedentary',
      light: 'Lightly active',
      moderate: 'Moderately active',
      active: 'Very active',
      very_active: 'Extremely active',
    },
    gender: {
      female: 'Female',
      male: 'Male',
      diverse: 'Diverse / Other',
    },
    meal: {
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      snack: 'Snack',
      custom: 'Custom',
    },
    meditationMode: {
      guided: 'Guided',
      free: 'Unguided',
      breathing: 'Breathing',
    },
    meditationTopic: {
      morning: 'Morning',
      mindfulness: 'Mindfulness',
      energy: 'Energy',
      focus: 'Focus & Concentration',
      relaxation: 'Relaxation',
      calm: 'Calm',
      stress_relief: 'Stress Relief',
      sleep: 'Sleep',
    },
    meditationSoundCategory: {
      meditation_music: 'Meditation Music',
      ambient: 'Ambient Sounds',
      nature: 'Nature Sounds',
    },
  },
  tabs: {
    home: 'Home',
    profile: 'Profile',
    fasting: 'Fasting',
    nutrition: 'Nutrition',
    activity: 'Activity',
    meditation: 'Meditation',
    statistics: 'Statistics',
  },
  nav: {
    goHome: 'Go to Home',
  },
  splash: {
    tagline: 'Fasting · Nutrition · Activity · Meditation',
  },
  home: {
    greeting: {
      morning: 'Good morning',
      afternoon: 'Good afternoon',
      evening: 'Good evening',
    },
    pulse: {
      title: "Today's pulse",
      onTrack: 'On track',
      goalExceeded: 'Goal exceeded',
      kcalRemaining: 'kcal remaining',
      kcalOver: 'kcal over',
      fastingStreak: '{{days}}d fasting streak',
      mindfulStreak: '{{days}}d mindful streak',
    },
    ring: {
      nutrition: 'Nutrition',
      activity: 'Activity',
      mindfulness: 'Mindfulness',
    },
    today: {
      title: 'Today',
      consumedToday: 'Consumed today',
      activity: 'Activity',
      meditation: 'Meditation',
      streak: 'Streak',
      netKcal: 'Net kcal',
    },
  },
  history: {
    title: 'History',
    allGoals: 'All goals',
    emptyTitle: 'No history yet',
    emptyMessage: 'Activity across all {{appName}} modules will show up here.',
    filters: {
      fasting: 'Fasting',
      nutrition: 'Nutrition',
      activity: 'Activity',
      weight: 'Weight',
      meditation: 'Meditation',
    },
  },
  onboarding: {
    stepProgress: 'Step {{step}} of {{total}}',
    welcome: {
      tagline: 'Your health, beautifully aligned.',
      begin: 'Start',
      /** Not an existing tab — the other four feature chips on this screen reuse `tabs.*` directly instead of duplicating those labels here. */
      wellness: 'Wellness',
    },
    goals: {
      heading: 'What brings you to HealthyMe?',
      subheading: "Choose what you'd like to focus on. We'll personalize your experience.",
      recommendation: 'Choose up to 3 to start — you can add more any time.',
      items: {
        fitness: { title: 'Get Fit & Build Strength', subtitle: 'Training, strength, structure' },
        activity: { title: 'Be More Active', subtitle: 'Move more, every day' },
        yoga: { title: 'Practice Yoga', subtitle: 'Flexibility & mindful movement' },
        meditation: { title: 'Meditate & Feel Better', subtitle: 'Calm, focus, better sleep' },
        fasting: { title: 'Improve My Fasting', subtitle: 'Build a rhythm that works for you' },
        nutrition: { title: 'Eat Better', subtitle: 'Track and improve what you eat' },
        overall: { title: 'Improve Overall Health', subtitle: 'A bit of everything' },
      },
      primary: {
        eyebrow: 'MAIN FOCUS',
        title: "What's your main focus right now?",
        subtitle: 'The rest stay part of your experience too — this just decides what comes first.',
      },
    },
    goalQuestions: {
      fitness: {
        level: {
          title: "What's your fitness level?",
          options: { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced' },
        },
        where: {
          title: 'Where do you usually train?',
          options: { home: 'At Home', gym: 'At the Gym', both: 'Both' },
        },
        targets: {
          title: 'What are you working toward?',
          options: { muscle: 'Build Muscle', fat_loss: 'Lose Fat', strength: 'Get Stronger', fitness: 'Improve Fitness', consistency: 'Stay Consistent' },
        },
        frequency: {
          title: 'How often would you like to train?',
          options: { two: '2 days/week', three: '3 days/week', four: '4 days/week', five_plus: '5+ days/week' },
        },
      },
      activity: {
        enjoy: {
          title: 'What activities do you enjoy?',
          options: { walking: 'Walking', running: 'Running', cycling: 'Cycling', hiking: 'Outdoor Activity', other: 'General Movement' },
        },
        improve: {
          title: 'What would you like to improve?',
          options: { daily_movement: 'Daily movement', endurance: 'Endurance', distance: 'Distance', pace: 'Pace / speed', consistency: 'Consistency' },
        },
      },
      yoga: {
        experience: {
          title: "What's your yoga experience?",
          options: { new: 'New to Yoga', some: 'Some Experience', regular: 'Regular Practice' },
        },
        focus: {
          title: 'What would you like from yoga?',
          options: { flexibility: 'Flexibility', mobility: 'Mobility', relaxation: 'Relaxation', strength: 'Strength', balance: 'Balance', stress_relief: 'Stress Relief' },
        },
        sessionLength: {
          title: 'How long should a typical session feel?',
          options: { short: '5–10 min', medium: '15–20 min', long: '30 min', extended: '45+ min' },
        },
      },
      meditation: {
        help: {
          title: 'What would you like meditation to help with?',
          options: { stress_relief: 'Stress Relief', sleep: 'Better Sleep', focus: 'Focus & Concentration', calm: 'Calm', mindfulness: 'Mindfulness', energy: 'Energy', relaxation: 'Relaxation' },
        },
        familiarity: {
          title: 'How familiar are you with meditation?',
          options: { new: "I'm new", tried: "I've tried it", regular: 'I meditate regularly' },
        },
        sessionLength: {
          title: 'What session length feels right?',
          options: { five: '5 min', fifteen: '15 min', thirty: '30 min', forty_five_plus: '45+ min' },
        },
      },
      fasting: {
        familiarity: {
          title: 'How familiar are you with fasting?',
          options: { new: "I'm new", tried: "I've tried fasting", regular: 'I fast regularly' },
        },
        lookingFor: {
          title: 'What are you looking for?',
          options: { routine: 'Build a routine', track: 'Track fasting time', consistency: 'Improve consistency', explore: 'Explore fasting schedules' },
        },
        schedule: {
          title: 'Which fasting schedule interests you?',
          options: { fourteen_ten: '14:10', sixteen_eight: '16:8', eighteen_six: '18:6', twenty_four: '20:4' },
        },
      },
      nutrition: {
        focus: {
          title: 'What would you like to focus on?',
          options: { eat_healthier: 'Eat Healthier', track_calories: 'Track Calories', protein: 'Improve Protein Intake' },
        },
      },
      overall: {
        matters: {
          title: 'What matters most to you?',
          options: { move: 'Move more', eat: 'Eat better', sleep: 'Sleep / relax better', consistency: 'Build consistency', fitness: 'Improve fitness', mindfulness: 'Mindfulness' },
        },
      },
    },
    goalSummary: {
      title: 'HealthyMe is ready for you.',
      yourFocus: 'Your focus',
      /** `{{items}}` is a plain, already-joined list (e.g. "strength training, short mindfulness sessions and nutrition tracking") — built deterministically from `goalSummary.blurbs`, never generated text. */
      body: 'Your experience will prioritize {{items}}.',
      blurbs: {
        fitness: 'strength training',
        activity: 'daily movement',
        yoga: 'mindful movement',
        meditation: 'short mindfulness sessions',
        fasting: 'a fasting rhythm that fits you',
        nutrition: 'nutrition tracking',
        overall: 'a balanced routine across the essentials',
      },
      continueCta: 'Continue',
    },
    goal: {
      eyebrow: 'YOUR GOAL',
      title: 'What do you want to achieve?',
      options: {
        weight_loss: { title: 'Lose weight', outcome: 'A steady calorie deficit, built into your daily target.' },
        maintenance: { title: 'Maintain weight', outcome: 'Hold steady — your targets track your baseline exactly.' },
        muscle_gain: { title: 'Gain weight', outcome: 'A controlled surplus to support muscle, not just the scale.' },
      },
    },
    personalize: {
      title: 'Your Profile',
      next: "Let's go",
      subtitle: 'A few quick things and {{appName}} will {{tagline}}.',
      whatWeUse: "What we'll use",
      taglineFallback: 'help you build a plan that actually fits',
      taglines: {
        weight_loss: 'help you reach a steady weight-loss target',
        maintenance: 'help you hold steady, right where you are',
        muscle_gain: 'help you build, with a target that supports it',
      },
      items: {
        body: 'A few body basics',
        birthday: 'Your birthday',
        nutrients: 'What nutrients to prioritize',
      },
    },
    gender: {
      title: "Let's start with you",
      subtitle: 'This calibrates your baseline calculations.',
    },
    age: {
      title: "When's your birthday?",
      subtitle: 'Used to calibrate your baseline calculations.',
      label: 'Date of birth',
    },
    height: {
      title: 'How tall are you?',
      subtitle: 'Drag to set your height — watch your profile scale.',
      info: 'Using your height, we can calculate your calorie expenditure.',
    },
    weight: {
      title: "What's your weight?",
      subtitle: 'Drag to set your current weight.',
      info: 'Using your weight and height, the algorithm estimates your approximate body fat percentage.',
      reassurance: 'A visual reference for your profile — never a judgment.',
    },
    activityLevel: {
      title: 'How active are you?',
      subtitle: 'Feeds your estimated daily energy use.',
      options: {
        sedentary: { desc: 'Little to no exercise, desk job.' },
        light: { desc: 'Light exercise 1–3 days a week.' },
        moderate: { desc: 'Moderate exercise 3–5 days a week.' },
        active: { desc: 'Hard exercise 6–7 days a week.' },
        very_active: { desc: 'Physical job or twice-daily training.' },
      },
    },
    micronutrients: {
      title: 'Micronutrient Setup',
      subtitle: "We've pre-selected what matters most for your goal — tap any to adjust.",
      next: 'Build my plan',
      trackedOf: 'of {{count}} nutrients tracked',
      categories: {
        vitamins: 'Vitamins',
        minerals: 'Minerals',
        other: 'Other essentials',
      },
    },
    complete: {
      readyTitle: 'Your plan is ready',
      readySubtitle: 'Built from your profile — every number below adjusts as you go.',
      dailyCalorieTarget: 'Daily calorie target',
      statuses: {
        analyzing: 'Analyzing your profile…',
        calculating: 'Calculating your baseline…',
        personalizing: 'Personalizing your plan…',
      },
      goal: 'Goal',
      activityLevel: 'Activity level',
      heightWeight: 'Height · Weight',
      micronutrients: 'Micronutrients',
      carbs: 'Carbs',
      protein: 'Protein',
      fat: 'Fat',
      enter: 'Enter {{appName}}',
    },
  },
  auth: {
    mockNotice: 'Authentication is mocked locally for this prototype.',
    login: {
      title: 'Welcome back',
      subtitle: 'Log in to continue your {{appName}} routine.',
      email: 'Email',
      emailPlaceholder: 'Enter your email',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      emailInvalid: 'Please enter a valid email address.',
      passwordRequired: 'Please enter your password.',
      forgotPassword: 'Forgot password?',
      submit: 'Log in',
      newToApp: 'New to {{appName}}?',
      createAccount: 'Create an account',
    },
    register: {
      title: 'Create your account',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      password: 'Password',
      submit: 'Create account',
      haveAccount: 'Already have an account?',
      logIn: 'Log in',
    },
    forgotPassword: {
      title: 'Reset password',
      intro: "Enter the email associated with your account and we'll send reset instructions.",
      email: 'Email',
      submit: 'Send reset link',
      sent: 'If an account exists for {{email}}, a reset link has been sent.',
    },
    address: {
      title: 'Where should we ship to?',
      subtitle: 'Used for the {{appName}} webshop — orders and deliveries.',
      label: 'Street address, city, postal code',
      submit: 'Continue',
    },
    emailVerification: {
      title: 'Verify your email',
      verifiedTitle: 'Email verified',
      sentTo: 'We sent a verification link to {{email}}.',
      yourEmail: 'your email',
      verifiedBody: 'Your account is fully set up.',
      verifiedButton: "I've verified my email",
    },
  },
  profile: {
    title: 'Profile',
    height: 'Height',
    weight: 'Weight',
    activityLevel: 'Activity level',
    goal: 'Goal',
    editProfile: 'Edit profile',
    settings: 'Settings',
    healthIntegrations: 'Health integrations',
    sendFeedback: 'Send feedback',
    privacy: 'Privacy',
    logout: 'Log out',
    goBack: 'Go back',
  },
  editProfile: {
    title: 'Edit profile',
    firstName: 'First name',
    lastName: 'Last name',
    heightCm: 'Height (cm)',
    weightKg: 'Weight (kg)',
    profilePicture: 'Profile picture',
    changePhoto: 'Change profile picture',
    initial: 'Initial',
    save: 'Save changes',
  },
  avatarPicker: {
    title: 'Choose your avatar',
    subtitle: 'Pick a look, or keep your initial',
    useInitial: 'Use initial',
    initial: 'Initial',
    avatarLabel: '{{name}} avatar',
    cancel: 'Cancel',
    done: 'Done',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: {
      light: 'Light',
      dark: 'Dark',
      system: 'System',
    },
    units: {
      title: 'Units',
      metric: 'Metric',
      imperial: 'Imperial',
    },
    language: {
      title: 'Language',
    },
    liveMoments: {
      title: 'Fasting timeline "live moments"',
      showCards: 'Show live moment cards',
      haptics: 'Haptic feedback',
    },
    data: {
      title: 'Data',
      healthIntegrations: 'Health integrations',
      privacy: 'Privacy & data',
      dataManagement: 'Data management',
    },
    support: {
      title: 'Support',
      feedback: 'Send feedback',
    },
  },
  notifications: {
    title: 'Notifications',
    empty: 'No notifications yet',
    emptyMessage: 'Reminders and milestones will appear here.',
    markAllRead: 'Mark all as read',
  },
  fasting: {
    title: 'Fasting',
    startFast: 'Start fasting',
    viewActiveFast: 'View active fast',
    startFastShort: 'Start fast',
    active: 'Active',
    noActiveFast: 'No active fast',
    noActiveFastBody: 'Choose a method and start tracking your fasting window.',
    elapsed: '{{duration}} elapsed',
    goalTimeReached: 'Goal time reached',
    remaining: '{{duration}} remaining',
    plannedEnd: '{{duration}} · planned end at {{time}}',
    stats: {
      currentStreak: 'Current streak',
      completed: 'Completed',
      avgDuration: 'Avg. duration',
      longest: 'Longest',
    },
    menu: {
      history: 'Fasting history',
      calendar: 'Fasting calendar',
      statistics: 'Fasting statistics',
      plans: 'My fasting plans',
      settings: 'Fasting settings',
    },
    chooseMethod: 'Choose a method',
  },
  nutrition: {
    title: 'Nutrition',
    noItemsLogged: 'No items logged',
    itemsSummary: '{{kcal}} kcal · {{count}} items',
    ofKcal: 'of {{target}} kcal',
    kcalRemaining: '{{amount}} kcal remaining',
    goalExceededBy: 'Goal exceeded by {{amount}} kcal',
    emptyTitle: 'Nothing logged yet',
    emptyMessage: "Add your first meal to see today's nutrition.",
    quickAddTitle: 'Quick add',
    endFastPrompt: {
      title: 'You have an active fast',
      message: 'Logging food usually means an eating window has started. End your current fast now?',
      keepFasting: 'Keep fasting',
      endFast: 'End fast',
    },
    quickAdd: {
      barcode: 'Scan barcode',
      aiPhoto: 'AI photo',
      aiVoice: 'AI voice',
      aiText: 'AI text',
    },
    menu: {
      recipes: 'My recipes',
      foods: 'My foods',
      favorites: 'Favorites',
      goals: 'Nutrition goals',
      history: 'Nutrition history',
    },
    macros: {
      carbs: 'Carbs',
      protein: 'Protein',
      fat: 'Fat',
    },
  },
  activity: {
    title: 'Activity',
    startActivity: 'Start activity',
    logManually: 'Log manually',
    viewAllActivity: 'View all activity',
    viewFullHistory: 'View full history',
    recentActivities: 'Recent activities',
    inProgress: '{{type}} in progress',
    tapToResume: 'Tap to resume tracking',
    emptyTitle: 'No activities yet',
    emptyMessage: 'Start a workout or log one manually to see it here.',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    finish: 'Finish',
    distance: 'Distance',
    pace: 'Pace',
    duration: 'Duration',
  },
  meditation: {
    title: 'Meditation',
    findYourCalm: 'Find your calm',
    subtitle: 'Meditation for a better you',
    today: 'Today',
    streak: 'Streak',
    dayShort: 'day',
    startMeditation: 'Start meditation',
    quickSessions: 'Quick sessions',
    viewAll: 'View all',
    viewAllQuickSessions: 'View all quick sessions',
    quick: {
      short: 'Short',
      shortSub: '3 min',
      guided: 'Guided',
      guidedSub: 'Sessions',
      breathing: 'Breathing',
      breathingSub: 'Exercises',
      free: 'Unguided',
      freeSub: 'Meditate',
    },
    menu: {
      templates: 'My templates',
      templatesSub: 'Your saved meditations',
      goals: 'Goals',
      goalsSub: 'Track your progress',
      history: 'History',
      historySub: 'Your past sessions',
      statistics: 'Statistics',
      statisticsSub: 'Insights and trends',
      reminders: 'Reminders',
      remindersSub: 'Stay consistent',
    },
    exitConfirm: {
      title: 'End meditation?',
      message: 'Are you sure you want to leave this meditation session?',
      continue: 'Continue Meditation',
      end: 'End Session',
    },
    ambient: {
      control: 'Background Sound',
      title: 'Soundscape',
      subtitle: 'Optional background sound for this session',
      none: 'None',
      recommended: 'Recommended',
      comingSoon: 'Coming Soon',
      unavailable: 'Background sound unavailable — continuing without it',
      volume: 'Volume',
      sounds: {
        rain: 'Rain',
        ocean: 'Ocean',
        forest: 'Forest',
        fire: 'Fireplace',
        ambient: 'Ambient',
      },
    },
    player: {
      comingSoonBody: 'This session is coming soon.',
      wellDone: 'Well done',
      minCompleted: '{{minutes}} min completed',
      ofMin: 'of {{minutes}} min',
      preparing: 'Preparing your meditation…',
      audioUnavailable: 'Audio unavailable — continuing without sound',
      pause: 'Pause',
      resume: 'Resume',
      fallbackTitle: 'Meditation',
      unguidedFallbackTitle: 'Unguided meditation',
    },
    details: {
      notFoundTitle: 'Meditation',
      unavailableTitle: 'Meditation unavailable',
      unavailableBody: 'This content may have been deactivated or archived.',
      removeFavorite: 'Remove from favorites',
      addFavorite: 'Add to favorites',
      comingSoon: 'Coming soon',
      start: 'Start meditation',
    },
    categories: {
      all: 'All',
      guidedTitle: 'Guided meditations',
      unguidedTitle: 'Unguided meditations',
      tryMeditationMusic: 'Try Meditation Music',
      clearFilters: 'Clear filters',
      showAllTopic: 'Show all {{topic}}',
      descriptorDuration: '{{minutes}}-minute session',
      descriptorSound: '{{sound}} session',
      descriptorDurationSound: '{{minutes}}-minute {{sound}} session',
      emptyGeneric: 'Nothing is available yet.',
      emptyForTopic: 'Nothing is available for {{topic}} yet.',
      emptyWithDescriptor: 'No {{descriptor}} is available yet.',
      emptyForTopicWithDescriptor: 'No {{descriptor}} is available for {{topic}} yet.',
    },
    favoritesScreen: {
      title: 'Favorites',
      empty: 'No favorites yet',
    },
    historyScreen: {
      title: 'Meditation history',
      empty: 'No sessions yet',
      statusCompleted: 'Completed',
      statusEndedEarly: 'Ended early',
    },
    statisticsScreen: {
      title: 'Meditation statistics',
      noData: 'No data available yet.',
      totalSessions: 'Total sessions',
      totalTime: 'Total time',
      averageDuration: 'Average duration',
      longestSession: 'Longest session',
      currentStreak: 'Current streak',
    },
    remindersScreen: {
      title: 'Reminders',
      disclaimer: "Reminders never count as a completed meditation — they're just a nudge.",
      time: 'Time',
      days: 'Repeat on',
      add: 'Add reminder',
      empty: 'No meditation reminders yet',
      everyDay: 'Every day',
      weekdays: 'Weekdays',
      selectAtLeastOneDay: 'Choose at least one day.',
      savingWhileOff: "This reminder is off — saving keeps it off. Use the switch to turn it on.",
      permissionDenied: "Notifications are turned off for {{appName}}, so this reminder can't be scheduled. Enable notifications in your device settings to turn it on.",
      notificationTitle: 'Time for meditation',
      notificationBody: 'Take a few minutes for yourself.',
    },
    goalsScreen: {
      title: 'Meditation goals',
      goalExceeded: 'Goal exceeded',
      type: {
        meditation_minutes: 'Meditation minutes',
        meditation_sessions: 'Meditation sessions',
      },
    },
    templatesScreen: {
      title: 'My templates',
      newTemplate: 'New template',
      name: 'Name',
      durationMinutes: 'Duration (minutes)',
      saveTemplate: 'Save template',
      empty: 'No templates yet',
      emptyBody: 'Save a personal meditation configuration to reuse it in one tap.',
    },
    breathing: {
      unavailable: 'Breathing scheme unavailable',
      getComfortable: 'Get comfortable',
      breatheIn: 'Breathe In',
      hold: 'Hold',
      breatheOut: 'Breathe Out',
      ready: 'Ready',
      start: 'Start breathing exercise',
      stop: 'Stop',
      wellDone: 'Well done',
      cycleProgress: 'Cycle {{current}} of {{total}}',
      voiceGuidanceOn: 'Voice guidance on',
      voiceGuidanceOff: 'Voice guidance off',
      background: {
        none: 'None',
        meditationMusic: 'Meditation Music',
        ambient: 'Ambient',
        nature: 'Nature',
      },
    },
  },
  statistics: {
    title: 'Statistics',
    noData: 'Not enough data yet',
    period: {
      day: 'Day',
      week: 'Week',
      month: 'Month',
      year: 'Year',
      total: 'Total',
    },
  },
  weight: {
    loggedOn: 'Logged {{date}}',
    noEntries: 'No entries yet',
    manual: 'Manual',
  },
  feedback: {
    title: 'Feedback',
    intro: "We read every message — tell us what's working or what isn't.",
    category: {
      improvement: {
        title: 'Suggest improvement',
        description: 'Something works, but could work better.',
      },
      bug: {
        title: 'Report a bug',
        description: 'Something is broken or behaving unexpectedly.',
      },
      feature: {
        title: 'Suggest a feature',
        description: "Something you wish {{appName}} could do.",
      },
      general: {
        title: 'General feedback',
        description: 'Anything else on your mind.',
      },
    },
    messageLabel: 'Your message',
    messagePlaceholder: 'Tell us more…',
    validationRequired: 'Please add a message before submitting.',
    submit: 'Send feedback',
    submitting: 'Sending…',
    success: {
      title: 'Thank you',
      body: "Your feedback has been received — it genuinely helps shape what we build next.",
      done: 'Done',
    },
  },
  states: {
    errorTitle: 'Something went wrong',
    errorBody: 'Please try again.',
    retry: 'Retry',
    emptyTitle: 'Nothing here yet',
  },
};
